apiVersion: v1
kind: Namespace
metadata:
  name: karma-prod-namespace
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: karmadb-config
data:
  DB_HOST: "karma.l17qn.mongodb.net"
  DB_PORT: "27017"
  ENV: "prod"
  MONGO_CLUSTER_NAME: "karma"
