apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmadb-deployment
  labels:
    app: karmadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karmadb-k8s
  template:
    metadata:
      labels:
        # Label of the mongodb pod. Useful for identification of pod.
        app: karmadb-k8s
    spec:
      containers:
      - name: karmadb-k8s
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: 1024Mi
            cpu: "1"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: karmadb-secret
              key: DB_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: karmadb-secret
              key: DB_PASS
        volumeMounts:
        - name: karmadb-data
          mountPath: /data/db
      volumes:
      - name: karmadb-data
        persistentVolumeClaim:
          claimName: karmadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: karmadb-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: karmadb-k8s
